// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAitjUwikrfTdb7bIudN3DMM7lPRz87WQU',
    appId: '1:786188074556:web:35cc898da40fbb3c7e4d39',
    messagingSenderId: '786188074556',
    projectId: 'abdelrahman-wael',
    authDomain: 'abdelrahman-wael.firebaseapp.com',
    databaseURL: 'https://abdelrahman-wael-default-rtdb.firebaseio.com',
    storageBucket: 'abdelrahman-wael.firebasestorage.app',
    measurementId: 'G-TTC8NJGLDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx3DS8H6W0VFvMqEhtqwqdIbt1r-nk8go',
    appId: '1:786188074556:android:0f6cb06cad4454fe7e4d39',
    messagingSenderId: '786188074556',
    projectId: 'abdelrahman-wael',
    databaseURL: 'https://abdelrahman-wael-default-rtdb.firebaseio.com',
    storageBucket: 'abdelrahman-wael.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZB1eUQeXxv0wPvm_HOSfIY-lSU9fqrJA',
    appId: '1:786188074556:ios:1550d6c078b564e37e4d39',
    messagingSenderId: '786188074556',
    projectId: 'abdelrahman-wael',
    databaseURL: 'https://abdelrahman-wael-default-rtdb.firebaseio.com',
    storageBucket: 'abdelrahman-wael.firebasestorage.app',
    iosBundleId: 'com.example.dysphagia',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZB1eUQeXxv0wPvm_HOSfIY-lSU9fqrJA',
    appId: '1:786188074556:ios:1550d6c078b564e37e4d39',
    messagingSenderId: '786188074556',
    projectId: 'abdelrahman-wael',
    databaseURL: 'https://abdelrahman-wael-default-rtdb.firebaseio.com',
    storageBucket: 'abdelrahman-wael.firebasestorage.app',
    iosBundleId: 'com.example.dysphagia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRYDGxdCoCMwKneA0_aAmDxlhnmCdYaF8',
    appId: '1:786188074556:web:d823ef7e9a8ba4117e4d39',
    messagingSenderId: '786188074556',
    projectId: 'abdelrahman-wael',
    authDomain: 'abdelrahman-wael.firebaseapp.com',
    databaseURL: 'https://abdelrahman-wael-default-rtdb.firebaseio.com',
    storageBucket: 'abdelrahman-wael.firebasestorage.app',
    measurementId: 'G-NTC4XVHRJL',
  );
}
